version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=director
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres

  web2py:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
